### ISSUE TITLE
Bug in version 3.2.0

### ISSUE THREAD

**Issue by mbaillif** [reds-heig/logisim-evolution#308] opened 2019-12-20 19:04 UTC
If in place a free text on a schema, even just one.
There's this message when you're save the circuit.
"Text component not found."
3.2.0 from Branch develop

**Comment by BFH-ktt1** [comment] 2019-12-20 19:19
I can reproduce, thanks for the catch!

**Comment by BFH-ktt1** [comment] 2019-12-29 14:25
Fixed in my latest push, closing the issue, please reopen if the problem is not solved.

**Closed by BFH-ktt1** 2019-12-29 14:25 UTC
Labels: bug, normal priority

**Comment by micahwagner** [comment] 2021-04-21 14:41
every time I put text down in a schematic scheme and try to save, it says "Text component not found." for every text component in the scheme. This does not happen when I put text in a circuit appearance.

**Comment by micahwagner** [comment] 2021-04-21 14:42
I have the newest version of logisim-evolution

**Comment by micahwagner** [comment] 2021-04-23 19:35
the version I'm talking about is 3.4.4

**Comment by micahwagner** [comment] 2021-04-23 19:36
sorry for mentioning it again, I didn't know it was tracked already
