### ISSUE TITLE
Combinatorical Analysis generates non-minimized circuits, and refuses to connect multiple inputs to a output.

### ISSUE THREAD

**Issue by jay20162016** [reds-heig/logisim-evolution#428] opened 2020-08-06 15:14 UTC
For example, this is part of the circuit generated:
![image of circuit](https://user-images.githubusercontent.com/20290260/89548839-848c1400-d7d5-11ea-8d95-84685251c0f0.png)
This circuit could be minimized by having the final NAND connect to the output of the previous circuit twice. 
Here is a truth table to reproduce the output:
```
# Truth table
# Generated from circuit test

inpu[2..0] | outpu[9..0]
~~~~~~~~~~~~~~~~~~~~~~~~
   000     | 0001110011 
   001     | 0100111111 
   010     | 1010000000 
   011     | 0111110011 
   100     | 0000001000 
   101     | 1000010110 
   110     | 0011100001 
   111     | 1100001100 
```

**Comment by BFH-ktt1** [comment] 2020-08-07 08:30
Dear @jay20162016, I am unable to reproduce this effect in logisim-evolution V3.3.6. From what I can see from the circuit you are using an old version of logisim-evolution (probably a 2.x) .
Could you:
1) Please try your circuit again in the latest version of logisim-evolution.
2) Please indicate for which bit of the outpu this circuit is generated
With this info I can than trace down the problem. I close the issue for now, please reopen when the problem still persists in the latest version of logisim evolution.

**Closed by BFH-ktt1** 2020-08-07 08:30 UTC

**Comment by jay20162016** [comment] 2020-08-07 13:20
I am using the new version, but I cannot reproduce it.
