### ISSUE TITLE
Cannot Load Memory Image Files

### ISSUE THREAD

**Issue by mfbutner** [reds-heig/logisim-evolution#446] opened 2020-10-31 19:55 UTC
I am unable to load memory image files to either RAM or ROM in version 3.3.1. This seems independent of the format that the file is saved in. I tried
- v2.0 raw
- v3.0 hex words addressed
- v3.0 hex words plain

I know it is not a formatting issue with the files because I would edit a memory file (which works) and save its contents to a file (which also works) but when I would go back to load the image I just saved, nothing happens (the contents of memory don't change).

**Comment by BFH-ktt1** [comment] 2020-11-03 07:28
Thank you for your bug report. I look into the details as soon as I find some time. This might take a while as the COVID-situation takes much of my "free time".

**Comment by BFH-ktt1** [comment] 2020-11-19 11:08
Dear @mfbutner , I could not reproduce your bug on the latest version (3.3.6). Could you please give that one a try and post some test-files in case you can observe the same problem. I close the issue for now, please reopen if the problem still persists in v3.3.6.

**Closed by BFH-ktt1** 2020-11-19 11:08 UTC
Labels: bug, normal priority

**Comment by mfbutner** [comment] 2020-11-20 02:04
3.3.6 Is working for me too :)
