### ISSUE TITLE
Text still broken

### ISSUE THREAD

**Issue by micahwagner** [reds-heig/logisim-evolution#549] opened 2021-04-21 15:16 UTC
every time I put text down in a schematic scheme and try to save, it says "Text component not found." for every text component in the scheme. This does not happen when I put text in a circuit appearance.

**Comment by BFH-ktt1** [comment] 2021-04-22 06:25
This is a duplicate of #544. A quick fix is available in the development tree, but not yet put in releases. Closing.

**Closed by BFH-ktt1** 2021-04-22 06:25 UTC

**Comment by micahwagner** [comment] 2021-04-22 14:13
oh ok that makes sense
