### ISSUE TITLE
Logisim-evolution don't keep saved custom circuit appearance when circuit is loaded as library.

### ISSUE THREAD

**Issue by nahinulsadad** [reds-heig/logisim-evolution#451] opened 2020-11-22 04:19 UTC
Logisim-evolution version: 3.36
OS: Windows 10
Java Version: 13.0.2 (JRE build 13.0.2+8)

I have saved the circuit appearance of FA when I opened it as file. Logisim-Evolution works just fine and keeps circuit appearance but it do not save facing of the circuit.

![image](https://user-images.githubusercontent.com/12844583/99893472-de441b80-2caa-11eb-9768-c6dd83366e19.png)

But when I load it as library in Logisim-Evolution, It don't keep correct circuit appearance and revert back to original appearance.

![image](https://user-images.githubusercontent.com/12844583/99893585-907be300-2cab-11eb-89da-105dd1b0dd06.png)

Even though other circuits in that library uses its correct appearance.

![image](https://user-images.githubusercontent.com/12844583/99893598-adb0b180-2cab-11eb-8cd2-42ec74cf778e.png)

I tried the same library (created in Logisim-Evolution) in Logisim-original and it works just fine.

Logisim-Evolution File:
[Clean_Multiplier_Library.zip](https://github.com/reds-heig/logisim-evolution/files/5578892/Clean_Multiplier_Library.zip)

**Comment by BFH-ktt1** [comment] 2020-11-22 07:30
Dear @nahinulsadad , thank you for your report. This issue is a kind of duplicate of #334 (I did not yet observe that the appearance inside the library is preserved, which gives me more info, thank you for that detail) and I will look into the details as soon as I have again some time available.

**Comment by BFH-ktt1** [comment] 2020-12-23 10:33
Is fixed in v3.4.0. Closing the issue, please reopen if the problem reappears

**Closed by BFH-ktt1** 2020-12-23 10:33 UTC
Labels: bug, duplicate, normal priority
