### ISSUE TITLE
bug in component RAM ROM

### ISSUE THREAD

**Issue by mbaillif** [reds-heig/logisim-evolution#314] opened 2020-01-04 22:11 UTC
The content editor does not work
Version 3.2 branch develop      
tested under windows

**Comment by maehne** [comment] 2020-01-04 23:25
This is a duplicate of issue #307, which is currently under investigation. Additionally, feedback is requested in issue #312 regarding the RAM/ROM components.

@BFH-ktt1: I suggest to close this issue.

**Comment by BFH-ktt1** [comment] 2020-01-04 23:56
@mbaillif : I will close this issue as it is a duplicate of #307, currently working on it and hope to have a solution soon.

**Closed by BFH-ktt1** 2020-01-04 23:56 UTC
